package dev.geode.ui

import dev.geode.data.Preset
import dev.geode.render.scene.SceneCapabilities
import dev.geode.render.scene.SceneParams

object BuiltInPresets {
    private data class Look(
        val name: String,
        val attack: Float,
        val decay: Float,
        val params: SceneParams,
    )

    private val LOOKS: List<Look> =
        listOf(
            Look(
                "Chill",
                0.4f,
                0.06f,
                SceneParams(
                    speed = 0.5f,
                    audioDrive = 0.85f,
                    beatResponse = 0.45f,
                    trails = true,
                    trailLength = 0.8f,
                    saturation = 0.8f,
                    brightness = 0.9f,
                    colorCycle = true,
                    cycleSpeed = 0.025f,
                    palette = 3,
                    sway = 0.35f,
                    vignette = 0.4f,
                    paramFadeSec = 1.5f,
                ),
            ),
            Look(
                "Punchy",
                0.85f,
                0.24f,
                SceneParams(
                    speed = 1.4f,
                    audioDrive = 1.6f,
                    beatResponse = 1.9f,
                    pulse = 0.6f,
                    flash = 0.4f,
                    bloom = 0.5f,
                    contrast = 1.2f,
                    intensity = 1.15f,
                    palette = 1,
                    bassGain = 1.4f,
                ),
            ),
            Look(
                "Hypno",
                0.5f,
                0.1f,
                SceneParams(
                    endlessZoom = true,
                    endlessZoomSpeed = 0.35f,
                    kaleidoscope = true,
                    symmetry = 6,
                    colorCycle = true,
                    cycleSpeed = 0.07f,
                    turbulence = 0.35f,
                    palette = 7,
                    warp = 0.3f,
                ),
            ),
            Look(
                "Vivid",
                0.6f,
                0.12f,
                SceneParams(
                    saturation = 1.35f,
                    intensity = 1.2f,
                    bloom = 0.4f,
                    palette = 5,
                    palette2 = 10,
                    paletteMix = 0.5f,
                    hueRange = 1.25f,
                    warp = 0.25f,
                    chromaAb = 0.3f,
                ),
            ),
            Look(
                "Retro",
                0.55f,
                0.14f,
                SceneParams(
                    speed = 0.9f,
                    palette = 2,
                    scanlines = 0.6f,
                    grain = 0.35f,
                    vignette = 0.5f,
                    posterize = 0.4f,
                    contrast = 1.1f,
                    saturation = 1.1f,
                ),
            ),
            Look(
                "Glitch",
                0.9f,
                0.3f,
                SceneParams(
                    speed = 1.2f,
                    audioDrive = 1.4f,
                    beatResponse = 1.6f,
                    glitch = 0.5f,
                    chromaAb = 0.5f,
                    shake = 0.4f,
                    palette = 8,
                    intensity = 1.1f,
                    trebGain = 1.5f,
                ),
            ),
            Look(
                "Dream",
                0.35f,
                0.05f,
                SceneParams(
                    speed = 0.45f,
                    trails = true,
                    trailLength = 0.85f,
                    bloom = 0.55f,
                    fisheye = 0.4f,
                    saturation = 0.9f,
                    brightness = 1.05f,
                    palette = 9,
                    paletteMix = 0.35f,
                    palette2 = 3,
                    driftX = 0.15f,
                    sway = 0.4f,
                ),
            ),
            Look(
                "Warp",
                0.6f,
                0.16f,
                SceneParams(
                    speed = 1.1f,
                    zoom = 1.1f,
                    twist = 0.5f,
                    warp = 0.5f,
                    morph = 0.4f,
                    turbulence = 0.6f,
                    palette = 4,
                    beatResponse = 1.3f,
                    pulse = 0.4f,
                ),
            ),
            Look(
                "Prism",
                0.5f,
                0.12f,
                SceneParams(
                    kaleidoscope = true,
                    symmetry = 8,
                    palette = 5,
                    palette2 = 7,
                    paletteMix = 0.6f,
                    saturation = 1.2f,
                    bloom = 0.35f,
                    rotation = 0.2f,
                    tile = 2f,
                ),
            ),
            Look(
                "Noir",
                0.55f,
                0.1f,
                SceneParams(
                    palette = 4,
                    saturation = 0.15f,
                    contrast = 1.35f,
                    vignette = 0.6f,
                    grain = 0.4f,
                    duotone = true,
                    brightness = 1.0f,
                ),
            ),
            Look(
                "Strobe",
                0.95f,
                0.35f,
                SceneParams(
                    speed = 1.5f,
                    audioDrive = 1.7f,
                    beatResponse = 2.0f,
                    strobe = 0.5f,
                    flash = 0.6f,
                    bloom = 0.45f,
                    palette = 1,
                    intensity = 1.2f,
                    bassGain = 1.5f,
                ),
            ),
            Look(
                "Deep",
                0.4f,
                0.07f,
                SceneParams(
                    endlessZoom = true,
                    endlessZoomSpeed = 0.5f,
                    zoom = 1.05f,
                    palette = 9,
                    saturation = 1.0f,
                    bloom = 0.4f,
                    vignette = 0.45f,
                    trails = true,
                    trailLength = 0.6f,
                ),
            ),
        )

    private val SHADER_VARIANTS: List<Preset> =
        listOf(
            Preset(
                name = "winter · Flurry",
                sceneId = dev.geode.render.scene.SceneIds.WINTER,
                attack = 0.5f,
                decay = 0.12f,
                customShader = null,
                params =
                    SceneParams(
                        palette = 9,
                        palette2 = 4,
                        paletteMix = 0.25f,
                        speed = 0.8f,
                        sway = 0.4f,
                        audioDrive = 1.1f,
                        beatResponse = 0.9f,
                        saturation = 0.85f,
                        brightness = 1.05f,
                        bloom = 0.35f,
                        vignette = 0.3f,
                        flowEnabled = true,
                        flowStrength = 0.55f,
                        flowCurl = 30f,
                        paramFadeSec = 1.0f,
                    ),
            ),
            Preset(
                name = "lava · Lamp",
                sceneId = dev.geode.render.scene.SceneIds.LAVA,
                attack = 0.3f,
                decay = 0.08f,
                customShader = null,
                params =
                    SceneParams(
                        palette = 1,
                        palette2 = 5,
                        paletteMix = 0.3f,
                        speed = 0.55f,
                        audioDrive = 1.0f,
                        beatResponse = 0.8f,
                        saturation = 1.15f,
                        brightness = 1.05f,
                        bloom = 0.45f,
                        vignette = 0.45f,
                        trails = true,
                        trailLength = 0.5f,
                        paramFadeSec = 2.0f,
                    ),
            ),
        )

    private val FLUID_VARIANTS: List<Preset> =
        listOf(
            Preset(
                name = "fluid · Inkdrop",
                sceneId = dev.geode.render.scene.SceneIds.FLUID,
                attack = 0.35f,
                decay = 0.5f,
                customShader = null,
                params =
                    SceneParams(
                        fluidBeatPattern = 0,
                        fluidBeatSplats = 2,
                        fluidStirrers = 1,
                        fluidStirrerSpeed = 0.5f,
                        fluidCurl = 20f,
                        fluidDensityDissipation = 0.35f,
                        fluidChromaticAging = 0.45f,
                        fluidSplatRadius = 0.16f,
                        fluidBloomIntensity = 0.5f,
                        fluidParticlesEnabled = false,
                        palette = 5,
                        fluidSpawnPath = 4,
                        fluidSpawnPoints = 1,
                        fluidCatchPoints = 0,
                    ),
            ),
            Preset(
                name = "fluid · Vortex",
                sceneId = dev.geode.render.scene.SceneIds.FLUID,
                attack = 0.5f,
                decay = 0.4f,
                customShader = null,
                params =
                    SceneParams(
                        fluidBeatPattern = 1,
                        fluidBeatSplats = 4,
                        fluidStirrers = 2,
                        fluidStirrerSpeed = 1.4f,
                        fluidCurl = 45f,
                        fluidChromaticAging = 0.5f,
                        fluidParticlesEnabled = true,
                        fluidParticleDrag = 0.35f,
                        palette = 2,
                        fluidSpawnPath = 0,
                        fluidSpawnPoints = 3,
                        fluidCatchPoints = 1,
                        fluidCatchPull = 1.6f,
                        fluidCatchRadius = 0.1f,
                    ),
            ),
            Preset(
                name = "fluid · Spectrum",
                sceneId = dev.geode.render.scene.SceneIds.FLUID,
                attack = 0.6f,
                decay = 0.35f,
                customShader = null,
                params =
                    SceneParams(
                        fluidBeatPattern = 3,
                        fluidBeatSplats = 6,
                        fluidStirrers = 0,
                        fluidBassPump = true,
                        fluidSunrays = true,
                        fluidSunraysWeight = 1.2f,
                        fluidFadeAudio = 1.0f,
                        fluidPaletteCycleSpeed = 1.2f,
                        colorCycle = true,
                        cycleSpeed = 0.05f,
                        palette = 3,
                        fluidSpawnPath = 1,
                        fluidSpawnPoints = 4,
                        fluidCatchPoints = 0,
                    ),
            ),
            Preset(
                name = "fluid · Nebula",
                sceneId = dev.geode.render.scene.SceneIds.FLUID,
                attack = 0.4f,
                decay = 0.55f,
                customShader = null,
                params =
                    SceneParams(
                        fluidDyeEnabled = false,
                        fluidParticlesEnabled = true,
                        fluidParticleDrag = 0.6f,
                        fluidParticleBrightness = 1.6f,
                        fluidCurl = 40f,
                        fluidStirrers = 3,
                        fluidStirrerSpeed = 0.8f,
                        fluidBloomIntensity = 1.1f,
                        palette = 7,
                        fluidSpawnPath = 3,
                        fluidSpawnPoints = 5,
                        fluidParticleLife = 9f,
                        fluidCatchPoints = 2,
                        fluidCatchPull = 1.2f,
                        fluidCatchRadius = 0.14f,
                    ),
            ),
            Preset(
                name = "fluid · Lava",
                sceneId = dev.geode.render.scene.SceneIds.FLUID,
                attack = 0.25f,
                decay = 0.7f,
                customShader = null,
                params =
                    SceneParams(
                        fluidChromaticAging = 1.0f,
                        fluidCurl = 15f,
                        fluidVelocityDissipation = 0.6f,
                        fluidDensityDissipation = 0.25f,
                        fluidSplatRadius = 0.22f,
                        fluidSplatForce = 0.7f,
                        fluidBloomIntensity = 1.2f,
                        fluidBloomThreshold = 0.4f,
                        fluidStirrerSpeed = 0.4f,
                        palette = 1,
                        fluidSpawnPath = 2,
                        fluidSpawnPoints = 2,
                        fluidCatchPoints = 0,
                        fluidSpawnProgress = 0.6f,
                    ),
            ),
            Preset(
                name = "fluid · Storm",
                sceneId = dev.geode.render.scene.SceneIds.FLUID,
                attack = 0.7f,
                decay = 0.25f,
                customShader = null,
                params =
                    SceneParams(
                        fluidBeatPattern = 2,
                        fluidBeatSplats = 5,
                        fluidStirrers = 4,
                        fluidStirrerSpeed = 1.8f,
                        fluidCurl = 50f,
                        fluidBassPump = true,
                        fluidParticlesEnabled = true,
                        fluidFadeAudio = 0.15f,
                        fluidSunrays = true,
                        palette = 6,
                        fluidSpawnPath = 4,
                        fluidSpawnPoints = 6,
                        fluidParticleLife = 3.5f,
                        fluidCatchPoints = 3,
                        fluidCatchPull = 2.2f,
                        fluidCatchRadius = 0.08f,
                    ),
            ),
            Preset(
                name = "fluid · Journey",
                sceneId = dev.geode.render.scene.SceneIds.FLUID,
                attack = 0.45f,
                decay = 0.45f,
                customShader = null,
                params =
                    SceneParams(
                        fluidSpawnPath = 2,
                        fluidSpawnPoints = 4,
                        fluidSpawnProgress = 1f,
                        fluidCatchPoints = 2,
                        fluidCatchPull = 1.4f,
                        fluidCatchRadius = 0.12f,
                        fluidParticleLife = 7f,
                        fluidBeatPattern = 1,
                        fluidBeatSplats = 3,
                        fluidStirrers = 2,
                        fluidChromaticAging = 0.4f,
                        fluidCurl = 35f,
                        colorCycle = true,
                        cycleSpeed = 0.03f,
                        palette = 16,
                    ),
            ),
            Preset(
                name = "water · Rainfall",
                sceneId = dev.geode.render.scene.SceneIds.WATER,
                attack = 0.45f,
                decay = 0.35f,
                customShader = null,
                params =
                    SceneParams(
                        waterDepth = 0.7f,
                        waterSpecular = 0.8f,
                        waterRippleStrength = 1.1f,
                        waterWaveSpeed = 1.0f,
                        waterFlow = 0.35f,
                        fluidBeatPattern = 1,
                        fluidBeatSplats = 3,
                        fluidStirrers = 1,
                        fluidStirrerSpeed = 0.6f,
                        fluidSparkle = true,
                        fluidSpawnPath = 3,
                        fluidSpawnPoints = 4,
                        fluidCatchPoints = 0,
                        palette = 3,
                    ),
            ),
            Preset(
                name = "curlflow · Streams",
                sceneId = dev.geode.render.scene.SceneIds.CURLFLOW,
                attack = 0.4f,
                decay = 0.5f,
                customShader = null,
                params =
                    SceneParams(
                        fluidSpawnPath = 1,
                        fluidSpawnPoints = 3,
                        fluidCatchPoints = 2,
                        fluidCatchPull = 1.2f,
                        fluidCatchRadius = 0.12f,
                        fluidParticleLife = 8f,
                        fluidParticleDrag = 0.4f,
                        turbulence = 0.7f,
                        audioDrive = 1.2f,
                        particleSize = 1.4f,
                        trails = true,
                        trailLength = 0.92f,
                        palette = 10,
                    ),
            ),
        )

    private val CYMATICS_VARIANTS: List<Preset> =
        listOf(
            Preset(
                name = "cymatics · CymaScope",
                sceneId = dev.geode.render.scene.SceneIds.CYMATICS,
                attack = 0.35f,
                decay = 0.4f,
                customShader = null,
                params =
                    SceneParams(
                        cymaticsGeometry = 0,
                        cymaticsFundamental = 110f,
                        cymaticsModes = 5,
                        cymaticsFocus = 0.7f,
                        cymaticsRing = 0.35f,
                        cymaticsScale = 3.4f,
                        cymaticsFill = 0.12f,
                        cymaticsLine = 1f,
                        cymaticsGlow = 1.1f,
                        cymaticsIridescence = 0.35f,
                        cymaticsCaustic = 0.8f,
                        cymaticsFlow = 0.25f,
                        cymaticsSwirl = 0.04f,
                        palette = 6,
                        hueRange = 0.5f,
                    ),
            ),
            Preset(
                name = "cymatics · Psychedelic",
                sceneId = dev.geode.render.scene.SceneIds.CYMATICS,
                attack = 0.3f,
                decay = 0.5f,
                customShader = null,
                params =
                    SceneParams(
                        cymaticsGeometry = 0,
                        cymaticsFundamental = 90f,
                        cymaticsModes = 3,
                        cymaticsFocus = 0.85f,
                        cymaticsRing = 0.55f,
                        cymaticsScale = 3.0f,
                        cymaticsFill = 1f,
                        cymaticsLine = 1.6f,
                        cymaticsGlow = 1.2f,
                        cymaticsIridescence = 1f,
                        cymaticsCaustic = 1f,
                        cymaticsFlow = 0.5f,
                        cymaticsSwirl = 0.06f,
                        palette = 0,
                    ),
            ),
            Preset(
                name = "cymatics · Chladni plate",
                sceneId = dev.geode.render.scene.SceneIds.CYMATICS,
                attack = 0.35f,
                decay = 0.45f,
                customShader = null,
                params =
                    SceneParams(
                        cymaticsGeometry = 1,
                        cymaticsFundamental = 82f,
                        cymaticsModes = 4,
                        cymaticsFocus = 0.9f,
                        cymaticsRing = 0.5f,
                        cymaticsScale = 1.15f,
                        cymaticsFill = 0.3f,
                        cymaticsLine = 1.1f,
                        cymaticsGlow = 0.9f,
                        cymaticsIridescence = 0.3f,
                        cymaticsCaustic = 0.7f,
                        cymaticsFlow = 0.15f,
                        cymaticsSwirl = 0f,
                        palette = 4,
                        hueRange = 0.6f,
                    ),
            ),
        )

    private val HYPERSPACE_VARIANTS: List<Preset> =
        listOf(
            Preset(
                name = "hyperspace · Breakthrough",
                sceneId = dev.geode.render.scene.SceneIds.HYPERSPACE,
                attack = 0.5f,
                decay = 0.35f,
                customShader = null,
                params =
                    SceneParams(
                        hyperJourney = dev.geode.render.scene.HyperspaceMath.JOURNEY_MUSIC,
                        hyperSpecies = 0,
                        hyperBodies = 1.2f,
                        hyperLifetime = 12f,
                        hyperSpin = 1.1f,
                        hyperOrbit = 1.1f,
                        hyperCamera = 1f,
                        hyperFold = 0.5f,
                        hyperGlow = 1.1f,
                        hyperNeon = 1.2f,
                        hyperField = 1f,
                        hyperHaze = 0.7f,
                        hyperTrap = 0.9f,
                        hyperMelt = 0.6f,
                        hyperStain = 0.55f,
                        hyperLiquid = 0.4f,
                        hyperRidges = 0.5f,
                        hyperStir = 1.1f,
                        palette = 0,
                        hueRange = 1f,
                    ),
            ),
            Preset(
                name = "hyperspace · Chrysanthemum",
                sceneId = dev.geode.render.scene.SceneIds.HYPERSPACE,
                attack = 0.4f,
                decay = 0.45f,
                customShader = null,
                params =
                    SceneParams(
                        hyperJourney = dev.geode.render.scene.HyperspaceMath.JOURNEY_HOLD,
                        hyperAct = dev.geode.render.scene.HyperspaceMath.Act.CHRYSANTHEMUM.ordinal,
                        hyperSpecies = 0,
                        hyperBodies = 1f,
                        hyperLifetime = 18f,
                        hyperSpin = 0.8f,
                        hyperOrbit = 0.7f,
                        hyperCamera = 0.7f,
                        hyperFold = 0.35f,
                        hyperGlow = 1f,
                        hyperNeon = 1.4f,
                        hyperField = 1.5f,
                        hyperHaze = 0.5f,
                        hyperMirrorFolds = 6,
                        hyperTrap = 1f,
                        hyperMelt = 0.3f,
                        hyperStain = 0.45f,
                        hyperLiquid = 0.3f,
                        hyperRidges = 0.7f,
                        hyperStir = 0.7f,
                        palette = 16,
                        hueRange = 0.9f,
                    ),
            ),
            Preset(
                name = "hyperspace · Coral garden",
                sceneId = dev.geode.render.scene.SceneIds.HYPERSPACE,
                attack = 0.3f,
                decay = 0.1f,
                customShader = null,
                params =
                    SceneParams(
                        speed = 0.6f,
                        hyperJourney = dev.geode.render.scene.HyperspaceMath.JOURNEY_CYCLE,
                        hyperCycleSeconds = 55f,
                        hyperSpecies = dev.geode.render.scene.HyperspaceMath.Species.CORAL.ordinal + 1,
                        hyperBodies = 0.8f,
                        hyperLifetime = 30f,
                        hyperSpin = 0.5f,
                        hyperOrbit = 0.45f,
                        hyperCamera = 0.5f,
                        hyperFold = 0.7f,
                        hyperGlow = 0.9f,
                        hyperNeon = 1.6f,
                        hyperField = 0.25f,
                        hyperHaze = 0.9f,
                        hyperTrap = 1.2f,
                        hyperMelt = 0.45f,
                        hyperStain = 0.7f,
                        hyperLiquid = 0.5f,
                        hyperRidges = 0.85f,
                        hyperStir = 0.6f,
                        hyperSwirl = 14f,
                        hyperFlowFade = 0.15f,
                        palette = 7,
                        hueRange = 0.8f,
                    ),
            ),
            Preset(
                name = "hyperspace · Molten",
                sceneId = dev.geode.render.scene.SceneIds.HYPERSPACE,
                attack = 0.55f,
                decay = 0.3f,
                customShader = null,
                params =
                    SceneParams(
                        hyperJourney = dev.geode.render.scene.HyperspaceMath.JOURNEY_MUSIC,
                        hyperSpecies = 0,
                        hyperBodies = 0.9f,
                        hyperLifetime = 10f,
                        hyperSpin = 0.8f,
                        hyperOrbit = 1.3f,
                        hyperFold = 0.55f,
                        hyperGlow = 1f,
                        hyperNeon = 1.5f,
                        hyperField = 0.5f,
                        hyperHaze = 0.6f,
                        hyperTrap = 0.7f,
                        hyperMelt = 1.35f,
                        hyperStain = 1f,
                        hyperLiquid = 0.75f,
                        hyperRidges = 1f,
                        hyperStir = 2f,
                        hyperSwirl = 40f,
                        hyperFlowFade = 0.12f,
                        hyperDetail = 0.8f,
                        palette = 10,
                        hueRange = 1.1f,
                    ),
            ),
        )

    val ALL: List<Preset> =
        SceneCapabilities.SHADER_SCENES.keys.flatMap { id ->
            LOOKS.map { look ->
                Preset(
                    name = "$id · ${look.name}",
                    sceneId = id,
                    attack = look.attack,
                    decay = look.decay,
                    customShader = null,
                    params = look.params,
                )
            }
        } + SHADER_VARIANTS + FLUID_VARIANTS + CYMATICS_VARIANTS + HYPERSPACE_VARIANTS

    fun isBuiltIn(name: String): Boolean = name.contains(" · ")
}
