// GENERATED by tools/import-theme-pack.sh - DO NOT EDIT BY HAND.
// Values are transcribed from each pack's tokens/{colors,theme.tokens}.json;
// re-run the importer with every shipped pack to regenerate.
package dev.musicviz.ui.theme

import androidx.compose.ui.graphics.Color
import dev.musicviz.R

/** Every crystal pack this build ships, in theme-picker order. */
object ThemePackCatalog {
    val clearQuartz =
        ThemePack(
            slug = "clear-quartz",
            name = "Clear Quartz",
            stone = "clear quartz",
            isLight = true,
            palette =
                StonePalette(
                    background = Color(0xFFEEEAE3),
                    backgroundDeep = Color(0xFFB8B0A5),
                    surface = Color(0xFFF7F4EE),
                    surfaceHigh = Color(0xFFFFFFFF),
                    primary = Color(0xFF9C7845),
                    secondary = Color(0xFF78898F),
                    accent = Color(0xFF6D5639),
                    glow = Color(0xFFFFF7DE),
                    onBackground = Color(0xFF181713),
                    onSurface = Color(0xFF1D1B17),
                    muted = Color(0xFF5D5951),
                    outline = Color(0xFF8E867A),
                    danger = Color(0xFFA13232),
                ),
            motion =
                StoneMotion(
                    pressDurationMs = 105,
                    pressScale = 0.972f,
                    innerGlowGain = 1.42f,
                    releaseDurationMs = 260,
                    focusDurationMs = 150,
                    edgeLightGain = 1.25f,
                    selectedDurationMs = 180,
                    reduceMotionCrossfadeMs = 120,
                ),
            material =
                StoneMaterial(
                    tile = R.drawable.tp_clear_quartz_material_tile,
                    glowOverlay = R.drawable.tp_clear_quartz_glow_overlay,
                    refractionOverlay = R.drawable.tp_clear_quartz_refraction_overlay,
                    ambientPortrait = R.drawable.tp_clear_quartz_ambient_portrait,
                    ambientLandscape = R.drawable.tp_clear_quartz_ambient_landscape,
                    ambientSquare = R.drawable.tp_clear_quartz_ambient_square,
                    backgroundOpacity = 0.38f,
                    surfaceOpacity = 0.72f,
                    disabledOpacity = 0.18f,
                ),
            sounds =
                StoneSounds(
                    click = R.raw.tp_clear_quartz_click_soft,
                    confirm = R.raw.tp_clear_quartz_confirm,
                    swoop = R.raw.tp_clear_quartz_swoop,
                ),
            surfaces =
                mapOf(
                    StoneComponent.ALBUM_TILE to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_album_tile_default,
                            focused = R.drawable.tp_clear_quartz_album_tile_focused,
                            pressed = R.drawable.tp_clear_quartz_album_tile_pressed,
                            selected = R.drawable.tp_clear_quartz_album_tile_selected,
                            disabled = R.drawable.tp_clear_quartz_album_tile_disabled,
                        ),
                    StoneComponent.BOTTOM_SHEET to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_bottom_sheet_default,
                            focused = R.drawable.tp_clear_quartz_bottom_sheet_focused,
                            pressed = R.drawable.tp_clear_quartz_bottom_sheet_pressed,
                            selected = R.drawable.tp_clear_quartz_bottom_sheet_selected,
                            disabled = R.drawable.tp_clear_quartz_bottom_sheet_disabled,
                        ),
                    StoneComponent.CARD to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_card_default,
                            focused = R.drawable.tp_clear_quartz_card_focused,
                            pressed = R.drawable.tp_clear_quartz_card_pressed,
                            selected = R.drawable.tp_clear_quartz_card_selected,
                            disabled = R.drawable.tp_clear_quartz_card_disabled,
                        ),
                    StoneComponent.CHIP to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_chip_default,
                            focused = R.drawable.tp_clear_quartz_chip_focused,
                            pressed = R.drawable.tp_clear_quartz_chip_pressed,
                            selected = R.drawable.tp_clear_quartz_chip_selected,
                            disabled = R.drawable.tp_clear_quartz_chip_disabled,
                        ),
                    StoneComponent.COMPACT_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_compact_button_default,
                            focused = R.drawable.tp_clear_quartz_compact_button_focused,
                            pressed = R.drawable.tp_clear_quartz_compact_button_pressed,
                            selected = R.drawable.tp_clear_quartz_compact_button_selected,
                            disabled = R.drawable.tp_clear_quartz_compact_button_disabled,
                        ),
                    StoneComponent.DIALOG to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_dialog_default,
                            focused = R.drawable.tp_clear_quartz_dialog_focused,
                            pressed = R.drawable.tp_clear_quartz_dialog_pressed,
                            selected = R.drawable.tp_clear_quartz_dialog_selected,
                            disabled = R.drawable.tp_clear_quartz_dialog_disabled,
                        ),
                    StoneComponent.ICON_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_icon_button_default,
                            focused = R.drawable.tp_clear_quartz_icon_button_focused,
                            pressed = R.drawable.tp_clear_quartz_icon_button_pressed,
                            selected = R.drawable.tp_clear_quartz_icon_button_selected,
                            disabled = R.drawable.tp_clear_quartz_icon_button_disabled,
                        ),
                    StoneComponent.KNOB to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_knob_default,
                            focused = R.drawable.tp_clear_quartz_knob_focused,
                            pressed = R.drawable.tp_clear_quartz_knob_pressed,
                            selected = R.drawable.tp_clear_quartz_knob_selected,
                            disabled = R.drawable.tp_clear_quartz_knob_disabled,
                        ),
                    StoneComponent.LIST_ROW to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_list_row_default,
                            focused = R.drawable.tp_clear_quartz_list_row_focused,
                            pressed = R.drawable.tp_clear_quartz_list_row_pressed,
                            selected = R.drawable.tp_clear_quartz_list_row_selected,
                            disabled = R.drawable.tp_clear_quartz_list_row_disabled,
                        ),
                    StoneComponent.MINI_PLAYER to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_mini_player_default,
                            focused = R.drawable.tp_clear_quartz_mini_player_focused,
                            pressed = R.drawable.tp_clear_quartz_mini_player_pressed,
                            selected = R.drawable.tp_clear_quartz_mini_player_selected,
                            disabled = R.drawable.tp_clear_quartz_mini_player_disabled,
                        ),
                    StoneComponent.NAVIGATION_BAR to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_navigation_bar_default,
                            focused = R.drawable.tp_clear_quartz_navigation_bar_focused,
                            pressed = R.drawable.tp_clear_quartz_navigation_bar_pressed,
                            selected = R.drawable.tp_clear_quartz_navigation_bar_selected,
                            disabled = R.drawable.tp_clear_quartz_navigation_bar_disabled,
                        ),
                    StoneComponent.PRIMARY_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_primary_button_default,
                            focused = R.drawable.tp_clear_quartz_primary_button_focused,
                            pressed = R.drawable.tp_clear_quartz_primary_button_pressed,
                            selected = R.drawable.tp_clear_quartz_primary_button_selected,
                            disabled = R.drawable.tp_clear_quartz_primary_button_disabled,
                        ),
                    StoneComponent.PROGRESS_RING to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_progress_ring_default,
                            focused = R.drawable.tp_clear_quartz_progress_ring_focused,
                            pressed = R.drawable.tp_clear_quartz_progress_ring_pressed,
                            selected = R.drawable.tp_clear_quartz_progress_ring_selected,
                            disabled = R.drawable.tp_clear_quartz_progress_ring_disabled,
                        ),
                    StoneComponent.SECONDARY_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_secondary_button_default,
                            focused = R.drawable.tp_clear_quartz_secondary_button_focused,
                            pressed = R.drawable.tp_clear_quartz_secondary_button_pressed,
                            selected = R.drawable.tp_clear_quartz_secondary_button_selected,
                            disabled = R.drawable.tp_clear_quartz_secondary_button_disabled,
                        ),
                    StoneComponent.SLIDER_THUMB to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_slider_thumb_default,
                            focused = R.drawable.tp_clear_quartz_slider_thumb_focused,
                            pressed = R.drawable.tp_clear_quartz_slider_thumb_pressed,
                            selected = R.drawable.tp_clear_quartz_slider_thumb_selected,
                            disabled = R.drawable.tp_clear_quartz_slider_thumb_disabled,
                        ),
                    StoneComponent.SLIDER_TRACK to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_slider_track_default,
                            focused = R.drawable.tp_clear_quartz_slider_track_focused,
                            pressed = R.drawable.tp_clear_quartz_slider_track_pressed,
                            selected = R.drawable.tp_clear_quartz_slider_track_selected,
                            disabled = R.drawable.tp_clear_quartz_slider_track_disabled,
                        ),
                    StoneComponent.TEXT_FIELD to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_text_field_default,
                            focused = R.drawable.tp_clear_quartz_text_field_focused,
                            pressed = R.drawable.tp_clear_quartz_text_field_pressed,
                            selected = R.drawable.tp_clear_quartz_text_field_selected,
                            disabled = R.drawable.tp_clear_quartz_text_field_disabled,
                        ),
                    StoneComponent.TOGGLE to
                        StoneStateArt(
                            default = R.drawable.tp_clear_quartz_toggle_default,
                            focused = R.drawable.tp_clear_quartz_toggle_focused,
                            pressed = R.drawable.tp_clear_quartz_toggle_pressed,
                            selected = R.drawable.tp_clear_quartz_toggle_selected,
                            disabled = R.drawable.tp_clear_quartz_toggle_disabled,
                        ),
                ),
        )

    val sugilite =
        ThemePack(
            slug = "sugilite",
            name = "Sugilite",
            stone = "sugilite",
            isLight = false,
            palette =
                StonePalette(
                    background = Color(0xFF120A1A),
                    backgroundDeep = Color(0xFF07040B),
                    surface = Color(0xFF281538),
                    surfaceHigh = Color(0xFF43205D),
                    primary = Color(0xFFB58AE8),
                    secondary = Color(0xFFD28BDD),
                    accent = Color(0xFFF2C2FF),
                    glow = Color(0xFFD9A8FF),
                    onBackground = Color(0xFFFBF5FF),
                    onSurface = Color(0xFFFBF5FF),
                    muted = Color(0xFFCDBED6),
                    outline = Color(0xFF745A80),
                    danger = Color(0xFFFF7F9C),
                ),
            motion =
                StoneMotion(
                    pressDurationMs = 105,
                    pressScale = 0.972f,
                    innerGlowGain = 1.42f,
                    releaseDurationMs = 255,
                    focusDurationMs = 150,
                    edgeLightGain = 1.25f,
                    selectedDurationMs = 180,
                    reduceMotionCrossfadeMs = 120,
                ),
            material =
                StoneMaterial(
                    tile = R.drawable.tp_sugilite_material_tile,
                    glowOverlay = R.drawable.tp_sugilite_glow_overlay,
                    refractionOverlay = R.drawable.tp_sugilite_refraction_overlay,
                    ambientPortrait = R.drawable.tp_sugilite_ambient_portrait,
                    ambientLandscape = R.drawable.tp_sugilite_ambient_landscape,
                    ambientSquare = R.drawable.tp_sugilite_ambient_square,
                    backgroundOpacity = 0.44f,
                    surfaceOpacity = 0.72f,
                    disabledOpacity = 0.18f,
                ),
            sounds =
                StoneSounds(
                    click = R.raw.tp_sugilite_click_soft,
                    confirm = R.raw.tp_sugilite_confirm,
                    swoop = R.raw.tp_sugilite_swoop,
                ),
            surfaces =
                mapOf(
                    StoneComponent.ALBUM_TILE to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_album_tile_default,
                            focused = R.drawable.tp_sugilite_album_tile_focused,
                            pressed = R.drawable.tp_sugilite_album_tile_pressed,
                            selected = R.drawable.tp_sugilite_album_tile_selected,
                            disabled = R.drawable.tp_sugilite_album_tile_disabled,
                        ),
                    StoneComponent.BOTTOM_SHEET to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_bottom_sheet_default,
                            focused = R.drawable.tp_sugilite_bottom_sheet_focused,
                            pressed = R.drawable.tp_sugilite_bottom_sheet_pressed,
                            selected = R.drawable.tp_sugilite_bottom_sheet_selected,
                            disabled = R.drawable.tp_sugilite_bottom_sheet_disabled,
                        ),
                    StoneComponent.CARD to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_card_default,
                            focused = R.drawable.tp_sugilite_card_focused,
                            pressed = R.drawable.tp_sugilite_card_pressed,
                            selected = R.drawable.tp_sugilite_card_selected,
                            disabled = R.drawable.tp_sugilite_card_disabled,
                        ),
                    StoneComponent.CHIP to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_chip_default,
                            focused = R.drawable.tp_sugilite_chip_focused,
                            pressed = R.drawable.tp_sugilite_chip_pressed,
                            selected = R.drawable.tp_sugilite_chip_selected,
                            disabled = R.drawable.tp_sugilite_chip_disabled,
                        ),
                    StoneComponent.COMPACT_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_compact_button_default,
                            focused = R.drawable.tp_sugilite_compact_button_focused,
                            pressed = R.drawable.tp_sugilite_compact_button_pressed,
                            selected = R.drawable.tp_sugilite_compact_button_selected,
                            disabled = R.drawable.tp_sugilite_compact_button_disabled,
                        ),
                    StoneComponent.DIALOG to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_dialog_default,
                            focused = R.drawable.tp_sugilite_dialog_focused,
                            pressed = R.drawable.tp_sugilite_dialog_pressed,
                            selected = R.drawable.tp_sugilite_dialog_selected,
                            disabled = R.drawable.tp_sugilite_dialog_disabled,
                        ),
                    StoneComponent.ICON_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_icon_button_default,
                            focused = R.drawable.tp_sugilite_icon_button_focused,
                            pressed = R.drawable.tp_sugilite_icon_button_pressed,
                            selected = R.drawable.tp_sugilite_icon_button_selected,
                            disabled = R.drawable.tp_sugilite_icon_button_disabled,
                        ),
                    StoneComponent.KNOB to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_knob_default,
                            focused = R.drawable.tp_sugilite_knob_focused,
                            pressed = R.drawable.tp_sugilite_knob_pressed,
                            selected = R.drawable.tp_sugilite_knob_selected,
                            disabled = R.drawable.tp_sugilite_knob_disabled,
                        ),
                    StoneComponent.LIST_ROW to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_list_row_default,
                            focused = R.drawable.tp_sugilite_list_row_focused,
                            pressed = R.drawable.tp_sugilite_list_row_pressed,
                            selected = R.drawable.tp_sugilite_list_row_selected,
                            disabled = R.drawable.tp_sugilite_list_row_disabled,
                        ),
                    StoneComponent.MINI_PLAYER to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_mini_player_default,
                            focused = R.drawable.tp_sugilite_mini_player_focused,
                            pressed = R.drawable.tp_sugilite_mini_player_pressed,
                            selected = R.drawable.tp_sugilite_mini_player_selected,
                            disabled = R.drawable.tp_sugilite_mini_player_disabled,
                        ),
                    StoneComponent.NAVIGATION_BAR to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_navigation_bar_default,
                            focused = R.drawable.tp_sugilite_navigation_bar_focused,
                            pressed = R.drawable.tp_sugilite_navigation_bar_pressed,
                            selected = R.drawable.tp_sugilite_navigation_bar_selected,
                            disabled = R.drawable.tp_sugilite_navigation_bar_disabled,
                        ),
                    StoneComponent.PRIMARY_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_primary_button_default,
                            focused = R.drawable.tp_sugilite_primary_button_focused,
                            pressed = R.drawable.tp_sugilite_primary_button_pressed,
                            selected = R.drawable.tp_sugilite_primary_button_selected,
                            disabled = R.drawable.tp_sugilite_primary_button_disabled,
                        ),
                    StoneComponent.PROGRESS_RING to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_progress_ring_default,
                            focused = R.drawable.tp_sugilite_progress_ring_focused,
                            pressed = R.drawable.tp_sugilite_progress_ring_pressed,
                            selected = R.drawable.tp_sugilite_progress_ring_selected,
                            disabled = R.drawable.tp_sugilite_progress_ring_disabled,
                        ),
                    StoneComponent.SECONDARY_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_secondary_button_default,
                            focused = R.drawable.tp_sugilite_secondary_button_focused,
                            pressed = R.drawable.tp_sugilite_secondary_button_pressed,
                            selected = R.drawable.tp_sugilite_secondary_button_selected,
                            disabled = R.drawable.tp_sugilite_secondary_button_disabled,
                        ),
                    StoneComponent.SLIDER_THUMB to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_slider_thumb_default,
                            focused = R.drawable.tp_sugilite_slider_thumb_focused,
                            pressed = R.drawable.tp_sugilite_slider_thumb_pressed,
                            selected = R.drawable.tp_sugilite_slider_thumb_selected,
                            disabled = R.drawable.tp_sugilite_slider_thumb_disabled,
                        ),
                    StoneComponent.SLIDER_TRACK to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_slider_track_default,
                            focused = R.drawable.tp_sugilite_slider_track_focused,
                            pressed = R.drawable.tp_sugilite_slider_track_pressed,
                            selected = R.drawable.tp_sugilite_slider_track_selected,
                            disabled = R.drawable.tp_sugilite_slider_track_disabled,
                        ),
                    StoneComponent.TEXT_FIELD to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_text_field_default,
                            focused = R.drawable.tp_sugilite_text_field_focused,
                            pressed = R.drawable.tp_sugilite_text_field_pressed,
                            selected = R.drawable.tp_sugilite_text_field_selected,
                            disabled = R.drawable.tp_sugilite_text_field_disabled,
                        ),
                    StoneComponent.TOGGLE to
                        StoneStateArt(
                            default = R.drawable.tp_sugilite_toggle_default,
                            focused = R.drawable.tp_sugilite_toggle_focused,
                            pressed = R.drawable.tp_sugilite_toggle_pressed,
                            selected = R.drawable.tp_sugilite_toggle_selected,
                            disabled = R.drawable.tp_sugilite_toggle_disabled,
                        ),
                ),
        )

    val mookaite =
        ThemePack(
            slug = "mookaite",
            name = "Mookaite",
            stone = "mookaite jasper",
            isLight = false,
            palette =
                StonePalette(
                    background = Color(0xFF21100E),
                    backgroundDeep = Color(0xFF0E0706),
                    surface = Color(0xFF593024),
                    surfaceHigh = Color(0xFF7B4432),
                    primary = Color(0xFFE4A54A),
                    secondary = Color(0xFFC36B50),
                    accent = Color(0xFFFFD890),
                    glow = Color(0xFFF0B55C),
                    onBackground = Color(0xFFFFF8E8),
                    onSurface = Color(0xFFFFF8E8),
                    muted = Color(0xFFE1C7AF),
                    outline = Color(0xFF8A6048),
                    danger = Color(0xFFFF8A79),
                ),
            motion =
                StoneMotion(
                    pressDurationMs = 105,
                    pressScale = 0.972f,
                    innerGlowGain = 1.42f,
                    releaseDurationMs = 245,
                    focusDurationMs = 150,
                    edgeLightGain = 1.25f,
                    selectedDurationMs = 180,
                    reduceMotionCrossfadeMs = 120,
                ),
            material =
                StoneMaterial(
                    tile = R.drawable.tp_mookaite_material_tile,
                    glowOverlay = R.drawable.tp_mookaite_glow_overlay,
                    refractionOverlay = R.drawable.tp_mookaite_refraction_overlay,
                    ambientPortrait = R.drawable.tp_mookaite_ambient_portrait,
                    ambientLandscape = R.drawable.tp_mookaite_ambient_landscape,
                    ambientSquare = R.drawable.tp_mookaite_ambient_square,
                    backgroundOpacity = 0.44f,
                    surfaceOpacity = 0.72f,
                    disabledOpacity = 0.18f,
                ),
            sounds =
                StoneSounds(
                    click = R.raw.tp_mookaite_click_soft,
                    confirm = R.raw.tp_mookaite_confirm,
                    swoop = R.raw.tp_mookaite_swoop,
                ),
            surfaces =
                mapOf(
                    StoneComponent.ALBUM_TILE to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_album_tile_default,
                            focused = R.drawable.tp_mookaite_album_tile_focused,
                            pressed = R.drawable.tp_mookaite_album_tile_pressed,
                            selected = R.drawable.tp_mookaite_album_tile_selected,
                            disabled = R.drawable.tp_mookaite_album_tile_disabled,
                        ),
                    StoneComponent.BOTTOM_SHEET to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_bottom_sheet_default,
                            focused = R.drawable.tp_mookaite_bottom_sheet_focused,
                            pressed = R.drawable.tp_mookaite_bottom_sheet_pressed,
                            selected = R.drawable.tp_mookaite_bottom_sheet_selected,
                            disabled = R.drawable.tp_mookaite_bottom_sheet_disabled,
                        ),
                    StoneComponent.CARD to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_card_default,
                            focused = R.drawable.tp_mookaite_card_focused,
                            pressed = R.drawable.tp_mookaite_card_pressed,
                            selected = R.drawable.tp_mookaite_card_selected,
                            disabled = R.drawable.tp_mookaite_card_disabled,
                        ),
                    StoneComponent.CHIP to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_chip_default,
                            focused = R.drawable.tp_mookaite_chip_focused,
                            pressed = R.drawable.tp_mookaite_chip_pressed,
                            selected = R.drawable.tp_mookaite_chip_selected,
                            disabled = R.drawable.tp_mookaite_chip_disabled,
                        ),
                    StoneComponent.COMPACT_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_compact_button_default,
                            focused = R.drawable.tp_mookaite_compact_button_focused,
                            pressed = R.drawable.tp_mookaite_compact_button_pressed,
                            selected = R.drawable.tp_mookaite_compact_button_selected,
                            disabled = R.drawable.tp_mookaite_compact_button_disabled,
                        ),
                    StoneComponent.DIALOG to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_dialog_default,
                            focused = R.drawable.tp_mookaite_dialog_focused,
                            pressed = R.drawable.tp_mookaite_dialog_pressed,
                            selected = R.drawable.tp_mookaite_dialog_selected,
                            disabled = R.drawable.tp_mookaite_dialog_disabled,
                        ),
                    StoneComponent.ICON_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_icon_button_default,
                            focused = R.drawable.tp_mookaite_icon_button_focused,
                            pressed = R.drawable.tp_mookaite_icon_button_pressed,
                            selected = R.drawable.tp_mookaite_icon_button_selected,
                            disabled = R.drawable.tp_mookaite_icon_button_disabled,
                        ),
                    StoneComponent.KNOB to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_knob_default,
                            focused = R.drawable.tp_mookaite_knob_focused,
                            pressed = R.drawable.tp_mookaite_knob_pressed,
                            selected = R.drawable.tp_mookaite_knob_selected,
                            disabled = R.drawable.tp_mookaite_knob_disabled,
                        ),
                    StoneComponent.LIST_ROW to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_list_row_default,
                            focused = R.drawable.tp_mookaite_list_row_focused,
                            pressed = R.drawable.tp_mookaite_list_row_pressed,
                            selected = R.drawable.tp_mookaite_list_row_selected,
                            disabled = R.drawable.tp_mookaite_list_row_disabled,
                        ),
                    StoneComponent.MINI_PLAYER to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_mini_player_default,
                            focused = R.drawable.tp_mookaite_mini_player_focused,
                            pressed = R.drawable.tp_mookaite_mini_player_pressed,
                            selected = R.drawable.tp_mookaite_mini_player_selected,
                            disabled = R.drawable.tp_mookaite_mini_player_disabled,
                        ),
                    StoneComponent.NAVIGATION_BAR to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_navigation_bar_default,
                            focused = R.drawable.tp_mookaite_navigation_bar_focused,
                            pressed = R.drawable.tp_mookaite_navigation_bar_pressed,
                            selected = R.drawable.tp_mookaite_navigation_bar_selected,
                            disabled = R.drawable.tp_mookaite_navigation_bar_disabled,
                        ),
                    StoneComponent.PRIMARY_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_primary_button_default,
                            focused = R.drawable.tp_mookaite_primary_button_focused,
                            pressed = R.drawable.tp_mookaite_primary_button_pressed,
                            selected = R.drawable.tp_mookaite_primary_button_selected,
                            disabled = R.drawable.tp_mookaite_primary_button_disabled,
                        ),
                    StoneComponent.PROGRESS_RING to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_progress_ring_default,
                            focused = R.drawable.tp_mookaite_progress_ring_focused,
                            pressed = R.drawable.tp_mookaite_progress_ring_pressed,
                            selected = R.drawable.tp_mookaite_progress_ring_selected,
                            disabled = R.drawable.tp_mookaite_progress_ring_disabled,
                        ),
                    StoneComponent.SECONDARY_BUTTON to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_secondary_button_default,
                            focused = R.drawable.tp_mookaite_secondary_button_focused,
                            pressed = R.drawable.tp_mookaite_secondary_button_pressed,
                            selected = R.drawable.tp_mookaite_secondary_button_selected,
                            disabled = R.drawable.tp_mookaite_secondary_button_disabled,
                        ),
                    StoneComponent.SLIDER_THUMB to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_slider_thumb_default,
                            focused = R.drawable.tp_mookaite_slider_thumb_focused,
                            pressed = R.drawable.tp_mookaite_slider_thumb_pressed,
                            selected = R.drawable.tp_mookaite_slider_thumb_selected,
                            disabled = R.drawable.tp_mookaite_slider_thumb_disabled,
                        ),
                    StoneComponent.SLIDER_TRACK to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_slider_track_default,
                            focused = R.drawable.tp_mookaite_slider_track_focused,
                            pressed = R.drawable.tp_mookaite_slider_track_pressed,
                            selected = R.drawable.tp_mookaite_slider_track_selected,
                            disabled = R.drawable.tp_mookaite_slider_track_disabled,
                        ),
                    StoneComponent.TEXT_FIELD to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_text_field_default,
                            focused = R.drawable.tp_mookaite_text_field_focused,
                            pressed = R.drawable.tp_mookaite_text_field_pressed,
                            selected = R.drawable.tp_mookaite_text_field_selected,
                            disabled = R.drawable.tp_mookaite_text_field_disabled,
                        ),
                    StoneComponent.TOGGLE to
                        StoneStateArt(
                            default = R.drawable.tp_mookaite_toggle_default,
                            focused = R.drawable.tp_mookaite_toggle_focused,
                            pressed = R.drawable.tp_mookaite_toggle_pressed,
                            selected = R.drawable.tp_mookaite_toggle_selected,
                            disabled = R.drawable.tp_mookaite_toggle_disabled,
                        ),
                ),
        )

    /** Picker order; the first entry is the app default. */
    val all: List<ThemePack> = listOf(clearQuartz, sugilite, mookaite)

    /** Pack for a persisted slug, or the default when unknown. */
    fun bySlug(slug: String?): ThemePack = all.firstOrNull { it.slug == slug } ?: all.first()
}
