package dev.musicviz.render.scene

import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin
import kotlin.math.sqrt
import kotlin.random.Random

/**
 * The maths behind the HYPERSPACE style: a room full of 3D fractals that are
 * each alive on their own clock, and a five-act story the music walks through.
 *
 * Nothing here touches GL. Everything is pure and deterministic given a seeded
 * [Random], so [dev.musicviz.HyperspaceMathTest] can pin the story law, the
 * lifecycles and the rotation algebra without a GPU; [HyperspaceScene] only
 * uploads what this file computes.
 *
 * ### Why a bank of bodies rather than one big fractal
 *
 * A single distance-estimated fractal is one rigid object: rotate it and every
 * part of it turns together, and it can neither appear nor leave. The
 * reference this style was built from - visionary/DMT art - is the opposite:
 * many separate growths, each turning on its own axis at its own rate, drifting
 * past each other, budding into existence and dissolving again.
 *
 * So the scene is a BANK of up to [MAX_BLOOMS] independent bodies ([Bloom]).
 * Each one carries:
 *
 *  - its own **species** ([Species]) - which fractal it is;
 *  - its own **spin**: two axis-angle rotations about two unrelated random
 *    axes at two unrelated rates, composed. One axis would be a spinning top,
 *    which reads as mechanical; two is a tumble that never repeats;
 *  - its own **orbit**: an ellipse in a randomly oriented plane, at its own
 *    angular rate, so the bodies move *in relation to each other* instead of
 *    sharing one global swirl;
 *  - its own **life**: it buds out of nothing, holds, and dissolves. The
 *    envelope is in [Bloom.fade], and the shader multiplies both the body's
 *    radius and its brightness by it, so a birth is a growth and not a pop.
 *
 * ### The five acts
 *
 * The story arc is the one the phenomenology literature describes for the
 * inhaled-DMT experience (see README and THIRD_PARTY_NOTICES): the visual
 * field sharpens, closes into a dense rotating filigree, gains depth, becomes
 * a place, and then opens. [Act] names those five stages and [HyperspaceJourney]
 * decides which one the track is in.
 *
 * The acts are not decoration: each one sets how many bodies live at once, how
 * strongly the background filigree is drawn, how close the camera sits and how
 * fast everything turns ([ActProfile]). Walking between them is what makes the
 * style tell a story over a track instead of looping one look.
 */
object HyperspaceMath {
    /** Hard ceiling on simultaneous bodies; sizes every uniform array. */
    const val MAX_BLOOMS: Int = 8

    /** Floats per body in each of the three packed `vec4` uniform arrays. */
    const val FLOATS_PER_VEC4: Int = 4

    /** Floats per body in the world -> local rotation uniform (`mat3`). */
    const val FLOATS_PER_MAT3: Int = 9

    /**
     * The fractal a body is. The four that carry the look are all built from
     * the same two moves - fold space, then invert or scale it - which is why
     * they can share one raymarcher; see `hyperspace_frag.glsl` for the
     * distance estimators themselves.
     */
    enum class Species {
        /**
         * Sphere packing: the limit set of the group generated by translations
         * of the unit cell and inversion in a sphere. Clusters of spheres
         * nested inside spheres, endlessly.
         */
        GASKET,

        /**
         * Kaleidoscopic IFS: sorted absolute-value folds plus a rotation
         * between iterations. Stepped, terraced, architectural - domes and
         * ziggurats stacked into each other.
         */
        TEMPLE,

        /**
         * Box fold + sphere fold + scale. Flat faceted panels meeting at hard
         * edges, which is what takes the neon rim best.
         */
        JEWEL,

        /**
         * Cell fold + sphere inversion with a floor on the inversion radius:
         * smooth branching tubes and ridged growths rather than facets.
         */
        CORAL,

        /**
         * The bulb: `z -> z^n + c` in the spherical-coordinate power that gives
         * a genuinely rounded, budded organic body. The most expensive of the
         * five (transcendentals in the inner loop), so it is iterated less.
         */
        BULB,
    }

    /** Species in ordinal order - `values()` allocates on every call. */
    val SPECIES: List<Species> = Species.entries.toList()

    /**
     * The five acts, in order. Names follow the phenomenology they are drawn
     * from; what each one *does* to the picture is in [profile].
     */
    enum class Act {
        /** The field sharpens. One distant body, the filigree barely there. */
        THRESHOLD,

        /** One dense rotating flower, mirrored into itself, filling the field. */
        CHRYSANTHEMUM,

        /** The flat texture gains depth: bodies separate out at real distances. */
        MAGIC_EYE,

        /** A place, not a pattern: bodies arrange around the viewer. */
        WAITING_ROOM,

        /** It opens. Every body at once, the widest palette, the fastest turn. */
        BREAKTHROUGH,
    }

    val ACTS: List<Act> = Act.entries.toList()

    /** Display names for the act selector. Index = [Act] ordinal. */
    val ACT_NAMES: List<String> =
        listOf("Threshold", "Chrysanthemum", "Magic eye", "Waiting room", "Breakthrough")

    /** How the journey decides which act it is in. Index = `hyperJourney`. */
    val JOURNEY_MODES: List<String> = listOf("Music", "Hold", "Cycle")

    const val JOURNEY_MUSIC: Int = 0
    const val JOURNEY_HOLD: Int = 1
    const val JOURNEY_CYCLE: Int = 2

    /**
     * What an act does to the picture. Every field is interpolated between
     * neighbouring acts by [profileAt], so a transition is a slow change of
     * conditions rather than a cut.
     */
    data class ActProfile(
        /** Bodies alive at once before the user's "Bodies" multiplier. */
        val bodies: Int,
        /** Weight of the background filigree, 0..1.5. */
        val field: Float,
        /** Kaleidoscopic mirror applied to the whole view, 0 = off. */
        val mirror: Float,
        /** Camera distance from the origin, in world units. */
        val camera: Float,
        /** Multiplier on every body's spin and orbit rate. */
        val motion: Float,
        /** Multiplier on emissive glow. */
        val glow: Float,
        /** Fraction of a turn of the colour wheel the act spreads over. */
        val hueSpread: Float,
    )

    /**
     * The act table. Read it top to bottom and it is the story: one far body
     * in a nearly empty field; one mirrored flower filling the screen; the
     * mirror releasing as bodies separate into depth; a close chamber of them;
     * then everything at once, wide open and fast.
     */
    val ACT_PROFILES: List<ActProfile> =
        listOf(
            // THRESHOLD
            ActProfile(bodies = 2, field = 0.22f, mirror = 0f, camera = 6.5f, motion = 0.45f, glow = 0.7f, hueSpread = 0.18f),
            // CHRYSANTHEMUM
            ActProfile(bodies = 3, field = 1.35f, mirror = 1f, camera = 9f, motion = 0.8f, glow = 1.1f, hueSpread = 0.55f),
            // MAGIC_EYE
            ActProfile(bodies = 5, field = 0.5f, mirror = 0f, camera = 5.4f, motion = 1f, glow = 1f, hueSpread = 0.7f),
            // WAITING_ROOM
            ActProfile(bodies = 7, field = 0.35f, mirror = 0f, camera = 4.2f, motion = 1.15f, glow = 1.2f, hueSpread = 0.85f),
            // BREAKTHROUGH - deliberately NOT mirrored. The mirror folds every
            // ray into one wedge of directions, which is what makes the
            // chrysanthemum a flat symmetric fabric; applying it here hid all
            // eight bodies behind a wedge that happened to contain none of
            // them. The breakthrough is the act that opens, so it opens.
            ActProfile(bodies = MAX_BLOOMS, field = 0.65f, mirror = 0f, camera = 5.2f, motion = 1.5f, glow = 1.45f, hueSpread = 1f),
        )

    /**
     * The act table read at a fractional act, so a journey between two acts is
     * a continuous change of every quantity rather than a jump. [act] is
     * clamped into `0 .. ACTS.size - 1`; body count rounds so it stays whole.
     */
    fun profileAt(act: Float): ActProfile {
        val x = act.coerceIn(0f, (ACT_PROFILES.size - 1).toFloat())
        val i = x.toInt().coerceAtMost(ACT_PROFILES.size - 2)
        val t = (x - i).coerceIn(0f, 1f)
        val a = ACT_PROFILES[i]
        val b = ACT_PROFILES[i + 1]

        fun f(
            u: Float,
            v: Float,
        ) = u + (v - u) * t
        return ActProfile(
            bodies = Math.round(f(a.bodies.toFloat(), b.bodies.toFloat())),
            field = f(a.field, b.field),
            mirror = f(a.mirror, b.mirror),
            camera = f(a.camera, b.camera),
            motion = f(a.motion, b.motion),
            glow = f(a.glow, b.glow),
            hueSpread = f(a.hueSpread, b.hueSpread),
        )
    }

    /** Seconds of loud music that walk the journey from act 0 to act 4. */
    const val RISE_SECONDS: Float = 26f

    /** Seconds of quiet that walk it back down. Slower: coming back takes longer. */
    const val FALL_SECONDS: Float = 44f

    /**
     * Loudness (as [dev.musicviz.analysis.AudioFeatures.macroEnergy], the
     * track's own dynamics envelope) above which the journey goes deeper and
     * below which it comes back. A verse sits under it, a chorus over it.
     */
    const val IMMERSION_PIVOT: Float = 0.42f

    /**
     * Shortest time an act may hold before another can be entered. Without it,
     * a track hovering at the pivot would re-target the body count several
     * times a second, and a body's whole life is a spawn and a despawn.
     */
    const val MIN_ACT_SECONDS: Float = 4f

    /**
     * Seconds the continuous act position takes to catch up with the journey's
     * own immersion. This is what makes the act change read as a drift rather
     * than a cut, since every [ActProfile] field is read at the smoothed value.
     */
    const val ACT_GLIDE_SECONDS: Float = 2.5f

    /**
     * Per-frame smoothing coefficient for a first-order lag with time constant
     * [seconds], frame-rate independent. Returns 1 (snap) for a zero or
     * negative constant.
     */
    fun smoothing(
        dt: Float,
        seconds: Float,
    ): Float {
        if (seconds <= 0f) return 1f
        return 1f - kotlin.math.exp(-dt / seconds)
    }

    /**
     * Composes two axis-angle rotations into ONE world -> local matrix, written
     * COLUMN-MAJOR so it can be handed to `glUniformMatrix3fv` untransposed and
     * consumed in GLSL as `uBloomRot[i] * (p - centre)`.
     *
     * The matrix returned is the INVERSE of the body's own orientation: the
     * raymarcher works by pulling the sample point into the body's frame, so
     * what it needs is world -> local. Both rotations are orthonormal, so the
     * inverse of their product is the transpose - which is what the index
     * arithmetic below writes out, without ever forming the forward matrix.
     *
     * @param out receives 9 floats at [offset].
     */
    fun worldToLocalRotation(
        axisA: FloatArray,
        angleA: Float,
        axisB: FloatArray,
        angleB: Float,
        out: FloatArray,
        offset: Int,
    ) {
        val a = FloatArray(9)
        val b = FloatArray(9)
        axisAngle(axisA, angleA, a)
        axisAngle(axisB, angleB, b)
        // Forward orientation is B*A (A applied first). World -> local is its
        // transpose, and (B*A)^T = A^T * B^T, so multiply the transposes in
        // the other order. Written straight into column-major storage.
        for (c in 0 until 3) {
            for (r in 0 until 3) {
                var sum = 0f
                for (k in 0 until 3) {
                    // a^T[r][k] = a[k][r], b^T[k][c] = b[c][k], both row-major here.
                    sum += a[k * 3 + r] * b[c * 3 + k]
                }
                // Column-major output: column c, row r.
                out[offset + c * 3 + r] = sum
            }
        }
    }

    /**
     * Rodrigues' rotation matrix for a unit [axis] and [angle], ROW-major
     * (`m[row * 3 + col]`). Internal to [worldToLocalRotation]; the axis is
     * normalized defensively so a degenerate axis yields identity rather than
     * NaN.
     */
    internal fun axisAngle(
        axis: FloatArray,
        angle: Float,
        out: FloatArray,
    ) {
        val len = sqrt(axis[0] * axis[0] + axis[1] * axis[1] + axis[2] * axis[2])
        if (len < 1e-6f) {
            out.fill(0f)
            out[0] = 1f
            out[4] = 1f
            out[8] = 1f
            return
        }
        val x = axis[0] / len
        val y = axis[1] / len
        val z = axis[2] / len
        val c = cos(angle)
        val s = sin(angle)
        val t = 1f - c
        out[0] = t * x * x + c
        out[1] = t * x * y - s * z
        out[2] = t * x * z + s * y
        out[3] = t * x * y + s * z
        out[4] = t * y * y + c
        out[5] = t * y * z - s * x
        out[6] = t * x * z - s * y
        out[7] = t * y * z + s * x
        out[8] = t * z * z + c
    }

    /**
     * GLSL's `mat3 * vec3` for a column-major matrix at [offset], so tests can
     * assert on exactly the arithmetic the shader will do.
     */
    fun transform(
        m: FloatArray,
        offset: Int,
        v: FloatArray,
        out: FloatArray,
    ) {
        for (r in 0 until 3) {
            out[r] = m[offset + r] * v[0] + m[offset + 3 + r] * v[1] + m[offset + 6 + r] * v[2]
        }
    }

    /** A uniformly distributed point on the unit sphere, written into [out]. */
    fun randomUnitVector(
        rng: Random,
        out: FloatArray,
        offset: Int = 0,
    ) {
        // Inverse-transform sampling on the cylinder: z uniform in [-1,1] and
        // the azimuth uniform gives an exactly uniform sphere (Archimedes),
        // where normalizing three gaussians or - worse - three uniforms would
        // bias toward the cube's corners.
        val z = rng.nextFloat() * 2f - 1f
        val a = rng.nextFloat() * 2f * PI.toFloat()
        val r = sqrt(max(0f, 1f - z * z))
        out[offset] = r * cos(a)
        out[offset + 1] = r * sin(a)
        out[offset + 2] = z
    }

    /**
     * An orthonormal pair spanning a random plane through the origin: the
     * plane a body orbits in. [u] is a random unit vector, [v] is a second one
     * made perpendicular to it by Gram-Schmidt.
     */
    fun randomPlane(
        rng: Random,
        u: FloatArray,
        v: FloatArray,
    ) {
        randomUnitVector(rng, u)
        randomUnitVector(rng, v)
        val d = u[0] * v[0] + u[1] * v[1] + u[2] * v[2]
        v[0] -= d * u[0]
        v[1] -= d * u[1]
        v[2] -= d * u[2]
        var len = sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
        if (len < 1e-4f) {
            // The two draws were (near) parallel: any perpendicular will do,
            // and the cross product with the least-aligned basis axis is the
            // numerically safest one.
            val ax = abs(u[0])
            val ay = abs(u[1])
            val az = abs(u[2])
            val bx = if (ax <= ay && ax <= az) 1f else 0f
            val by = if (ay < ax && ay <= az) 1f else 0f
            val bz = if (bx == 0f && by == 0f) 1f else 0f
            v[0] = u[1] * bz - u[2] * by
            v[1] = u[2] * bx - u[0] * bz
            v[2] = u[0] * by - u[1] * bx
            len = sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
        }
        v[0] /= len
        v[1] /= len
        v[2] /= len
    }

    /**
     * The birth/hold/death envelope of a body, 0..1.
     *
     * Both ends are smoothstepped, so a body swells out of nothing and
     * dissolves back into it; the shader multiplies the body's radius AND its
     * brightness by this, which is why a spawn is a growth rather than a pop.
     * [grow] and [wither] are clamped so they can never overlap into a body
     * that is never fully present.
     */
    fun lifeEnvelope(
        age: Float,
        lifetime: Float,
        grow: Float,
        wither: Float,
    ): Float {
        if (lifetime <= 0f) return 0f
        if (age <= 0f || age >= lifetime) return 0f
        val half = lifetime * 0.5f
        val g = grow.coerceIn(0.01f, half)
        val w = wither.coerceIn(0.01f, half)
        val rise = smoothstep(0f, g, age)
        val fall = 1f - smoothstep(lifetime - w, lifetime, age)
        return (rise * fall).coerceIn(0f, 1f)
    }

    fun smoothstep(
        edge0: Float,
        edge1: Float,
        x: Float,
    ): Float {
        if (edge1 <= edge0) return if (x < edge0) 0f else 1f
        val t = ((x - edge0) / (edge1 - edge0)).coerceIn(0f, 1f)
        return t * t * (3f - 2f * t)
    }

    /**
     * The fold/scale constant a species is iterated with, as a function of the
     * user's single "Fold" control (0..1) and the body's own jitter.
     *
     * Each species has its own usable band, and outside it the fractal either
     * collapses to a ball or explodes into noise, so one slider cannot be
     * shared raw - it is remapped per species here, once, where a test can
     * pin the endpoints.
     */
    fun foldFor(
        species: Species,
        fold: Float,
        jitter: Float,
    ): Float {
        val t = (fold.coerceIn(0f, 1f) + jitter * 0.12f).coerceIn(0f, 1f)
        return when (species) {
            // Inversion radius. Under ~0.8 the packing thins to dust, over
            // ~1.35 the spheres merge into one blob.
            Species.GASKET -> 0.85f + 0.48f * t
            // Rotation between IFS iterations, radians. 0 is the plain Menger
            // sponge; a fraction of a turn is what curls it into architecture.
            Species.TEMPLE -> 0.05f + 1.15f * t
            // Mandelbox scale. Negative scales fold the box inside out, which
            // is where the faceted panelled look lives.
            Species.JEWEL -> -2.4f + 1.5f * t
            // Cell half-size for the fold before the inversion: small cells
            // give thin tubes, large ones thick ridged trunks.
            Species.CORAL -> 0.55f + 0.55f * t
            // Bulb power. 8 is the classic; the band around it stays organic.
            Species.BULB -> 5f + 6f * t
        }
    }

    /**
     * Bounding radius of a species in its own local frame, before scaling.
     *
     * Two jobs, and both want it TIGHT. It is the sphere outside which the
     * raymarcher skips the estimator entirely, so an oversized one is paid for
     * on every ray; and it is what [HyperspaceLook.cameraDistance] keeps the
     * eye outside of, so an oversized one pushes the whole composition away.
     * Undersized is the real failure though - it clips the body's own
     * extremities off - so each is the enclosing radius of the fold domain
     * with a little headroom, not a guess.
     */
    fun localRadius(species: Species): Float =
        when (species) {
            // Fills the unit cell it folds into: sqrt(3) plus headroom.
            Species.GASKET -> 1.85f
            Species.TEMPLE -> 1.7f
            // The box fold's domain is the unit box, but the seed is added
            // back every iteration, so the attractor reaches further out.
            // Clipped tighter than this the box's own faceted silhouette is
            // cut away and it reads as a plain sphere with a texture on it.
            Species.JEWEL -> 3.2f
            Species.CORAL -> 2.1f
            Species.BULB -> 1.35f
        }

    /** The largest [localRadius] over every species - the worst-case body. */
    val MAX_LOCAL_RADIUS: Float = SPECIES.maxOf { localRadius(it) }
}

/**
 * One living fractal body. Created once and recycled: [spawn] gives a dead
 * slot a fresh identity, [advance] ages it, and [alive] goes false when its
 * life has run out. Fields are public and mutable because the bank steps
 * hundreds of them per second and a frame must allocate nothing.
 */
class Bloom {
    var alive: Boolean = false
        internal set

    var species: HyperspaceMath.Species = HyperspaceMath.Species.GASKET
        internal set

    /** Seconds since this body budded. */
    var age: Float = 0f
        internal set

    /** Total seconds this body will exist for. */
    var lifetime: Float = 0f
        internal set

    /** Birth/hold/death envelope, 0..1. See [HyperspaceMath.lifeEnvelope]. */
    var fade: Float = 0f
        internal set

    /** World-space centre, updated every frame from the orbit. */
    val centre: FloatArray = FloatArray(3)

    /** Orbit plane basis, orbit radii, rate and phase. */
    private val planeU = FloatArray(3)
    private val planeV = FloatArray(3)
    private var radiusU = 0f
    private var radiusV = 0f
    private var orbitRate = 0f
    private var orbitPhase = 0f

    /** Two spin axes and their (independent, signed) rates. */
    private val spinAxisA = FloatArray(3)
    private val spinAxisB = FloatArray(3)
    private var spinRateA = 0f
    private var spinRateB = 0f
    private var spinAngleA = 0f
    private var spinAngleB = 0f

    /** Local size of the fractal, in world units per local unit. */
    var scale: Float = 1f
        internal set

    /** Offset from the palette's base hue, in turns. */
    var hue: Float = 0f
        internal set

    /** Per-body jitter of the fold constant, -1..1. */
    var foldJitter: Float = 0f
        internal set

    /** Per-body emissive weight, around 1. */
    var glow: Float = 1f
        internal set

    /**
     * A per-body phase fed to the shader as a slow inner animation of the
     * fractal's own fold - the body breathing, distinct from its rotation.
     */
    var breath: Float = 0f
        internal set

    private var breathRate = 0f

    /**
     * Birth and death durations, held as state rather than derived from
     * [lifetime] each frame. [retire] shortens the life, and a wither read as
     * a fraction of the NEW life would then start in the past - the envelope
     * jumped from nearly 1 straight down to a fraction of it, which is the pop
     * this exists to prevent.
     */
    private var growSeconds = 0f
    private var witherSeconds = 0f

    /** Gives a dead slot a fresh identity. */
    fun spawn(
        rng: Random,
        species: HyperspaceMath.Species,
        lifetime: Float,
        spread: Float,
        sizeScale: Float,
    ) {
        this.species = species
        this.lifetime = max(lifetime, 0.5f)
        // A tenth of the life to bud and a fifth to dissolve: dying slower
        // than being born is what stops a busy act reading as a flicker of
        // bodies blinking in and out.
        growSeconds = this.lifetime * 0.1f
        witherSeconds = this.lifetime * 0.2f
        age = 0f
        fade = 0f
        alive = true
        HyperspaceMath.randomPlane(rng, planeU, planeV)
        // An ellipse, not a circle: two different radii in the orbit plane
        // means no two bodies trace the same shape even at the same rate.
        radiusU = spread * (0.35f + 0.85f * rng.nextFloat())
        radiusV = spread * (0.35f + 0.85f * rng.nextFloat())
        orbitRate = (0.035f + 0.16f * rng.nextFloat()) * if (rng.nextBoolean()) 1f else -1f
        orbitPhase = rng.nextFloat() * 2f * PI.toFloat()
        HyperspaceMath.randomUnitVector(rng, spinAxisA)
        HyperspaceMath.randomUnitVector(rng, spinAxisB)
        // Signed and unequal, so the two rotations never phase-lock into a
        // single spin about a fixed axis.
        spinRateA = (0.05f + 0.32f * rng.nextFloat()) * if (rng.nextBoolean()) 1f else -1f
        spinRateB = (0.03f + 0.19f * rng.nextFloat()) * if (rng.nextBoolean()) 1f else -1f
        spinAngleA = rng.nextFloat() * 2f * PI.toFloat()
        spinAngleB = rng.nextFloat() * 2f * PI.toFloat()
        scale = sizeScale * (0.55f + 0.9f * rng.nextFloat())
        hue = rng.nextFloat()
        foldJitter = rng.nextFloat() * 2f - 1f
        glow = 0.7f + 0.7f * rng.nextFloat()
        breath = rng.nextFloat() * 2f * PI.toFloat()
        breathRate = 0.08f + 0.22f * rng.nextFloat()
        advance(0f, 1f, 1f)
    }

    /**
     * Ages the body by [dt] and re-evaluates its orbit, spin and envelope.
     * [motion] scales every rate (the act's tempo), [orbitScale] the orbit
     * rate alone (the user's "Orbit drift").
     */
    fun advance(
        dt: Float,
        motion: Float,
        orbitScale: Float,
    ) {
        if (!alive) return
        age += dt
        if (age >= lifetime) {
            alive = false
            fade = 0f
            return
        }
        val m = max(motion, 0f)
        orbitPhase += dt * orbitRate * m * max(orbitScale, 0f) * 2f * PI.toFloat()
        spinAngleA += dt * spinRateA * m * 2f * PI.toFloat()
        spinAngleB += dt * spinRateB * m * 2f * PI.toFloat()
        breath += dt * breathRate * m
        val c = cos(orbitPhase)
        val s = sin(orbitPhase)
        for (i in 0 until 3) {
            centre[i] = planeU[i] * radiusU * c + planeV[i] * radiusV * s
        }
        fade =
            HyperspaceMath.lifeEnvelope(
                age = age,
                lifetime = lifetime,
                grow = growSeconds,
                wither = witherSeconds,
            )
    }

    /**
     * Brings the death forward, without cutting a body off mid-frame.
     *
     * The wither is shortened to match, which is the whole point: leaving it
     * at a fifth of the ORIGINAL life would put the start of the dissolve in
     * the past, and the envelope would drop from nearly 1 to a fraction of it
     * between one frame and the next.
     */
    fun retire(fadeSeconds: Float) {
        if (!alive) return
        val fade = max(fadeSeconds, 0.2f)
        val end = age + fade
        if (end < lifetime) {
            lifetime = end
            witherSeconds = min(witherSeconds, fade)
        }
    }

    /** Writes this body's two spin rotations as one world -> local `mat3`. */
    fun writeRotation(
        out: FloatArray,
        offset: Int,
    ) {
        HyperspaceMath.worldToLocalRotation(spinAxisA, spinAngleA, spinAxisB, spinAngleB, out, offset)
    }
}

/**
 * The bank of bodies: who is alive, who is being born, who is dissolving.
 *
 * Spawning is musical. A slot only fills on a transient - a body arrives ON a
 * hit rather than on a timer - unless nothing has been played for
 * [SILENT_SPAWN_SECONDS], in which case the bank seeds itself anyway so a
 * paused or ambient track is never an empty screen. Retiring is the reverse:
 * when an act asks for fewer bodies than are alive, the OLDEST is told to
 * dissolve, so the room thins out from the back.
 */
class BloomBank(
    private val rng: Random = Random.Default,
) {
    private companion object {
        /** Seconds without a transient after which a body spawns regardless. */
        const val SILENT_SPAWN_SECONDS = 2.5f

        /** Minimum gap between two spawns, so one drum fill is not eight bodies. */
        const val SPAWN_GAP_SECONDS = 0.45f

        /** Transient strength that counts as "something was played". */
        const val SPAWN_IMPULSE = 0.18f

        /** Seconds an over-quota body is given to dissolve. */
        const val RETIRE_SECONDS = 1.6f
    }

    val blooms: List<Bloom> = List(HyperspaceMath.MAX_BLOOMS) { Bloom() }

    private var sinceSpawn = SILENT_SPAWN_SECONDS
    private var sinceImpulse = 0f

    /** Bodies currently alive - what the shader will be asked to draw. */
    val aliveCount: Int
        get() = blooms.count { it.alive }

    fun reset() {
        for (b in blooms) {
            b.alive = false
            b.fade = 0f
        }
        sinceSpawn = SILENT_SPAWN_SECONDS
        sinceImpulse = 0f
    }

    /**
     * One frame of the bank.
     *
     * @param target how many bodies the act wants alive.
     * @param impulse this frame's transient strength (`AudioFeatures.motionImpulse`).
     * @param species the species new bodies take, or null to roll one per body.
     * @param lifetime base seconds a new body lives.
     * @param spread world radius the orbits are spread over.
     * @param sizeScale base local size of a new body.
     * @param motion the act's motion multiplier.
     * @param orbitScale the user's orbit-rate multiplier.
     */
    fun advance(
        dt: Float,
        target: Int,
        impulse: Float,
        species: HyperspaceMath.Species?,
        lifetime: Float,
        spread: Float,
        sizeScale: Float,
        motion: Float,
        orbitScale: Float,
    ) {
        for (b in blooms) b.advance(dt, motion, orbitScale)
        sinceSpawn += dt
        sinceImpulse = if (impulse >= SPAWN_IMPULSE) 0f else sinceImpulse + dt

        val want = target.coerceIn(0, HyperspaceMath.MAX_BLOOMS)
        var living = aliveCount
        // Too many: the oldest bodies are told to dissolve. Oldest first is
        // what makes the room feel like it is being emptied from the back
        // rather than randomly losing members.
        if (living > want) {
            var excess = living - want
            while (excess > 0) {
                val victim = blooms.filter { it.alive }.maxByOrNull { it.age } ?: break
                // Already retiring: nothing left to shorten, so stop rather
                // than spin looking for a victim that will not change.
                if (victim.lifetime - victim.age <= RETIRE_SECONDS) break
                victim.retire(RETIRE_SECONDS)
                excess--
            }
        }

        // Too few: fill a slot on the next transient, or - after a stretch of
        // silence - anyway, so an ambient passage still populates.
        if (living < want && sinceSpawn >= SPAWN_GAP_SECONDS) {
            val onHit = impulse >= SPAWN_IMPULSE
            val onSilence = sinceImpulse >= SILENT_SPAWN_SECONDS
            if (onHit || onSilence) {
                val slot = blooms.firstOrNull { !it.alive }
                if (slot != null) {
                    val pick = species ?: HyperspaceMath.SPECIES[rng.nextInt(HyperspaceMath.SPECIES.size)]
                    // +-35% on the base life, so a group spawned together does
                    // not later die together and empty the screen at once.
                    val life = lifetime * (0.65f + 0.7f * rng.nextFloat())
                    slot.spawn(rng, pick, life, spread, sizeScale)
                    sinceSpawn = 0f
                    living++
                }
            }
        }
    }

    /**
     * Packs every living body into the shader's four uniform arrays.
     *
     * Layout, mirrored by `hyperspace_frag.glsl`:
     * - [pos]   `xyz` world centre, `w` bounding radius (already faded);
     * - [shape] `x` species ordinal, `y` local scale, `z` fold constant,
     *           `w` life envelope;
     * - [look]  `x` hue offset, `y` glow, `z` breath phase, `w` unused;
     * - [rot]   world -> local rotation, column-major `mat3`.
     *
     * @return how many bodies were written, i.e. the shader's `uBloomCount`.
     */
    fun snapshot(
        fold: Float,
        pos: FloatArray,
        shape: FloatArray,
        look: FloatArray,
        rot: FloatArray,
        /**
         * World units to add to every bounding radius, for the distance the
         * melt can displace the geometry (`MeltMath.reach`). The sphere is
         * what lets a ray skip a body entirely, so a body pulled out of shape
         * by the medium would otherwise have its own edges cut off by the
         * bound it was skipped by.
         */
        boundInflate: Float = 0f,
    ): Int {
        var n = 0
        for (b in blooms) {
            if (!b.alive || b.fade <= 0.002f) continue
            if (n >= HyperspaceMath.MAX_BLOOMS) break
            val i4 = n * HyperspaceMath.FLOATS_PER_VEC4
            // The body GROWS: its world scale carries the envelope, so a birth
            // is a swelling and a death a shrinking rather than a fade of a
            // full-size object, which would read as a ghost.
            val worldScale = b.scale * (0.25f + 0.75f * b.fade)
            pos[i4] = b.centre[0]
            pos[i4 + 1] = b.centre[1]
            pos[i4 + 2] = b.centre[2]
            pos[i4 + 3] = HyperspaceMath.localRadius(b.species) * worldScale + boundInflate
            shape[i4] = b.species.ordinal.toFloat()
            shape[i4 + 1] = worldScale
            shape[i4 + 2] = HyperspaceMath.foldFor(b.species, fold, b.foldJitter)
            shape[i4 + 3] = b.fade
            look[i4] = b.hue
            look[i4 + 1] = b.glow
            look[i4 + 2] = b.breath
            look[i4 + 3] = 0f
            b.writeRotation(rot, n * HyperspaceMath.FLOATS_PER_MAT3)
            n++
        }
        return n
    }
}

/**
 * Where in the story the track is.
 *
 * In `Music` mode a single quantity moves: [immersion], 0..1, which rises
 * while the track is loud relative to its own dynamics and falls while it is
 * not ([HyperspaceMath.IMMERSION_PIVOT]). Multiplied out over the acts it
 * gives [actPosition], the continuous act the profile is read at, and rounding
 * that - held for at least [HyperspaceMath.MIN_ACT_SECONDS] - gives [act], the
 * discrete one the body count follows.
 *
 * `Hold` pins a chosen act. `Cycle` walks the five on a timer, for a set that
 * should tell the same story regardless of what is playing.
 */
class HyperspaceJourney {
    /** How deep the track has taken the journey, 0..1. */
    var immersion: Float = 0f
        private set

    /** Continuous position in the act list; every profile is read here. */
    var actPosition: Float = 0f
        private set

    /** The committed discrete act. Changes no faster than MIN_ACT_SECONDS. */
    var act: Int = 0
        private set

    private var heldSeconds = 0f
    private var cyclePhase = 0f

    fun reset() {
        immersion = 0f
        actPosition = 0f
        act = 0
        heldSeconds = 0f
        cyclePhase = 0f
    }

    /**
     * One frame of the story.
     *
     * @param energy the track's macro-dynamics envelope, 0..1 (falls back to
     *   RMS when offline analysis has not run).
     * @param mode one of [HyperspaceMath.JOURNEY_MUSIC] / `_HOLD` / `_CYCLE`.
     * @param holdAct the act `Hold` pins, and where `Cycle` starts.
     * @param cycleSeconds seconds per act in `Cycle`.
     * @param pace multiplier on how fast the journey moves (the Speed control).
     */
    fun advance(
        dt: Float,
        energy: Float,
        mode: Int,
        holdAct: Int,
        cycleSeconds: Float,
        pace: Float,
    ) {
        val last = HyperspaceMath.ACTS.size - 1
        val step = dt * max(pace, 0f)
        val goal: Float =
            when (mode) {
                HyperspaceMath.JOURNEY_HOLD -> holdAct.coerceIn(0, last).toFloat()
                HyperspaceMath.JOURNEY_CYCLE -> {
                    val per = max(cycleSeconds, 2f)
                    cyclePhase = (cyclePhase + step / per) % HyperspaceMath.ACTS.size.toFloat()
                    // Walks 0,1,2,3,4,0,... The wrap back to the threshold is
                    // the story restarting, which is what a set of tracks
                    // should do rather than sitting at breakthrough forever.
                    cyclePhase
                }
                else -> {
                    // Loud -> deeper, quiet -> back, and never at the same
                    // rate: RISE_SECONDS of a chorus takes the journey the
                    // whole way in, FALL_SECONDS of a verse the whole way out.
                    val drive = energy.coerceIn(0f, 1f) - HyperspaceMath.IMMERSION_PIVOT
                    val rate =
                        if (drive >= 0f) {
                            drive / (1f - HyperspaceMath.IMMERSION_PIVOT) / HyperspaceMath.RISE_SECONDS
                        } else {
                            drive / HyperspaceMath.IMMERSION_PIVOT / HyperspaceMath.FALL_SECONDS
                        }
                    immersion = (immersion + rate * step).coerceIn(0f, 1f)
                    immersion * last
                }
            }
        // Glide toward the goal so every ActProfile field changes continuously.
        actPosition += (goal - actPosition) * HyperspaceMath.smoothing(step, HyperspaceMath.ACT_GLIDE_SECONDS)
        actPosition = actPosition.coerceIn(0f, last.toFloat())
        heldSeconds += dt
        val rounded = Math.round(actPosition).coerceIn(0, last)
        if (rounded != act && heldSeconds >= HyperspaceMath.MIN_ACT_SECONDS) {
            act = rounded
            heldSeconds = 0f
        }
    }

    /** The interpolated profile at the current continuous act position. */
    fun profile(): HyperspaceMath.ActProfile = HyperspaceMath.profileAt(actPosition)
}

/**
 * The camera: a slow, never-repeating drift around the origin, plus the basis
 * the raymarcher builds its rays from.
 *
 * Kept here rather than in the shader so the drift is one testable formula and
 * so the scene can hand the shader a finished `mat3` instead of recomputing
 * three cross products per pixel. The path is a sum of three incommensurate
 * sinusoids per axis, which is what keeps it from ever visibly looping.
 */
class HyperspaceCamera {
    /** World position of the eye. */
    val position: FloatArray = FloatArray(3)

    /** Camera -> world basis as a column-major `mat3` (right, up, forward). */
    val basis: FloatArray = FloatArray(9)

    private var t = 0f

    fun reset() {
        t = 0f
    }

    /**
     * @param distance how far the eye sits from the origin (the act's camera).
     * @param drift multiplier on the drift rate; 0 parks the camera.
     * @param roll radians of roll about the view axis.
     */
    fun advance(
        dt: Float,
        distance: Float,
        drift: Float,
        roll: Float,
    ) {
        t += dt * max(drift, 0f)
        // Three incommensurate rates per angle: the ratios are irrational
        // enough that the path does not close, so the view never arrives back
        // where it started even over a long set.
        val yaw = 0.11f * t + 0.37f * sin(0.073f * t) + 0.13f * sin(0.191f * t)
        val pitch = 0.42f * sin(0.041f * t) + 0.17f * sin(0.113f * t)
        val d = max(distance, 0.35f)
        val cp = cos(pitch)
        position[0] = d * cp * cos(yaw)
        position[1] = d * sin(pitch)
        position[2] = d * cp * sin(yaw)

        // Look at the origin. Forward is -position normalized; up starts as
        // world +Y, rolled about forward, then orthonormalized.
        val inv = 1f / max(sqrt(position[0] * position[0] + position[1] * position[1] + position[2] * position[2]), 1e-5f)
        val fx = -position[0] * inv
        val fy = -position[1] * inv
        val fz = -position[2] * inv
        // World up, unless the view is nearly vertical - then the cross
        // product degenerates and the frame would flip.
        val upIsY = abs(fy) < 0.985f
        val ux = if (upIsY) 0f else 1f
        val uy = if (upIsY) 1f else 0f
        val uz = 0f
        // right = normalize(cross(forward, up))
        var rx = fy * uz - fz * uy
        var ry = fz * ux - fx * uz
        var rz = fx * uy - fy * ux
        val rl = 1f / max(sqrt(rx * rx + ry * ry + rz * rz), 1e-5f)
        rx *= rl
        ry *= rl
        rz *= rl
        // up = cross(right, forward)
        var vx = ry * fz - rz * fy
        var vy = rz * fx - rx * fz
        var vz = rx * fy - ry * fx
        if (roll != 0f) {
            val c = cos(roll)
            val s = sin(roll)
            val nrx = rx * c + vx * s
            val nry = ry * c + vy * s
            val nrz = rz * c + vz * s
            vx = vx * c - rx * s
            vy = vy * c - ry * s
            vz = vz * c - rz * s
            rx = nrx
            ry = nry
            rz = nrz
        }
        // Column-major: column 0 = right, 1 = up, 2 = forward.
        basis[0] = rx
        basis[1] = ry
        basis[2] = rz
        basis[3] = vx
        basis[4] = vy
        basis[5] = vz
        basis[6] = fx
        basis[7] = fy
        basis[8] = fz
    }
}

/**
 * Raymarcher budget for a given "Detail" setting, resolved on the CPU so the
 * shader's loops can be bounded by uniforms rather than by recompiling.
 *
 * Detail is one control because the three quantities have to move together:
 * more fractal iterations without more march steps just makes a thin surface
 * the ray steps over, and more steps without more iterations spends the budget
 * refining a shape that has no detail left to find.
 */
data class MarchBudget(
    val steps: Int,
    val iterations: Int,
    /** Iterations for [HyperspaceMath.Species.BULB], which costs several times more. */
    val bulbIterations: Int,
) {
    companion object {
        /** Matches the `MAX_STEPS` / `MAX_ITERS` compile-time bounds in the shader. */
        const val MAX_STEPS: Int = 128
        const val MAX_ITERS: Int = 14

        fun forDetail(detail: Float): MarchBudget {
            val d = detail.coerceIn(0.25f, 1.5f)
            return MarchBudget(
                steps = (48f + 56f * d).toInt().coerceIn(24, MAX_STEPS),
                iterations = (5f + 5f * d).toInt().coerceIn(3, MAX_ITERS),
                bulbIterations = (3f + 3f * d).toInt().coerceIn(2, 10),
            )
        }
    }
}

/**
 * Everything the shader needs that is not per-body: the act's interpolated
 * profile folded together with the user's controls, in one place so the scene
 * only uploads and the test can assert on the numbers.
 */
object HyperspaceLook {
    /**
     * How far apart the bodies are spread, in world units, at a given act.
     * Deeper acts hold more bodies, and packing more into the same volume
     * would just intersect them, so the spread grows with the count.
     */
    fun spread(bodies: Int): Float = 1.1f + 0.22f * bodies

    /**
     * Base local size of a new body. Shrinks as the room fills, so a
     * breakthrough is many small growths rather than a few enormous ones
     * overlapping into a single mass.
     */
    fun bodySize(bodies: Int): Float = (0.72f - 0.045f * bodies).coerceAtLeast(0.26f)

    /**
     * The largest world radius a body spawned at [bodySize] can reach: the
     * biggest species, at the top of [Bloom.spawn]'s size jitter.
     */
    fun maxBodyRadius(bodies: Int): Float = bodySize(bodies) * 1.45f * HyperspaceMath.MAX_LOCAL_RADIUS

    /**
     * How far the eye sits from the origin.
     *
     * The act asks for a distance, but it only gets it if that leaves the eye
     * OUTSIDE every body. Without the floor, the deeper acts - which are the
     * close ones, deliberately - put the camera inside a fractal, and a
     * raymarcher started inside a folded distance estimator does not draw the
     * inside of an object: it draws a screen of striped garbage, because the
     * estimate is only valid outside the set.
     */
    fun cameraDistance(
        actCamera: Float,
        spread: Float,
        maxBodyRadius: Float,
    ): Float = max(actCamera, spread + maxBodyRadius + 0.9f)

    /**
     * Bodies the act wants alive, after the user's density multiplier.
     * Floored at 1: an empty screen is never the right answer.
     */
    fun bodyTarget(
        profileBodies: Int,
        density: Float,
    ): Int = Math.round(profileBodies * density.coerceIn(0.1f, 2f)).coerceIn(1, HyperspaceMath.MAX_BLOOMS)

    /**
     * The distance the ray gives up at. Scales with the spread so a wide act
     * does not have its outermost bodies clipped away by the far plane.
     */
    fun farPlane(
        camera: Float,
        spread: Float,
    ): Float = camera + spread + 6f

    /**
     * Surface hit threshold, relative to the step's own distance from the eye:
     * a constant epsilon either shimmers in the distance or wastes steps up
     * close. Returned as the coefficient of `t` the shader multiplies.
     */
    const val HIT_EPSILON: Float = 0.0016f

    /**
     * Cheap-skip margin around a body's bounding sphere: outside it, the ray
     * steps by the distance to the sphere and the fractal is never evaluated.
     * This is what makes eight simultaneous distance-estimated fractals
     * affordable - a ray typically iterates one of them, not eight.
     *
     * Small but non-zero on purpose. At exactly zero the ray creeps: each step
     * lands on the sphere, where the bound is 0, and the march stalls without
     * ever entering the body.
     */
    const val BOUND_MARGIN: Float = 0.12f
}
