package dev.musicviz.render.scene

/** Stable identifiers shared by renderer, presets and the intelligence layer. */
object SceneIds {
    const val NEBULA: String = "nebula"
    const val BURSTS: String = "bursts"
    const val SWARM: String = "swarm"
    const val FOUNTAIN: String = "fountain"
    const val JULIA: String = "julia"
    const val TUNNEL: String = "tunnel"
    const val BARS: String = "bars"
    const val RING: String = "ring"
    const val SCOPE: String = "scope"
    const val PLASMA: String = "plasma"
    const val KALEIDO: String = "kaleido"
    const val WARP: String = "warp"
    const val GRID: String = "grid"
    const val VORONOI: String = "voronoi"
    const val MANDEL: String = "mandel"
    const val LISS: String = "liss"
    const val METABALLS: String = "metaballs"
    const val RIPPLES: String = "ripples"
    const val STARFIELD: String = "starfield"
    const val WAVES: String = "waves"
    const val HEXGRID: String = "hexgrid"
    const val SPIRAL: String = "spiral"
    const val AURORA: String = "aurora"
    const val SOLAR: String = "solar"
    const val ORBITS: String = "orbits"
    const val MILKDROP: String = "milkdrop"
    const val FLUID: String = "fluid"
    const val CURLFLOW: String = "curlflow"
    const val WATER: String = "water"
    const val CYMATICS: String = "cymatics"
}
